# Generated by Django 5.1.15 on 2026-06-30 17:26

import django.core.validators
import django.db.models.deletion
import ocorrencias.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('siape', models.CharField(max_length=20, unique=True, verbose_name='SIAPE')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, unique=True, verbose_name='Descrição')),
                ('nivel', models.CharField(choices=[('GRAVE', 'Grave'), ('MEDIA', 'Média'), ('LEVE', 'Leve')], default='LEVE', help_text='Usado para classificar a ocorrência nos indicadores do dashboard.', max_length=10, verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Tipo de Ocorrência',
                'verbose_name_plural': 'Tipos de Ocorrência',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='ocorrencias.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='Dia da semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário inicial')),
                ('horario_fim', models.TimeField(verbose_name='Horário final')),
                ('aula', models.CharField(help_text='Ex: "1ª Aula"', max_length=40, verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'ordering': ['dia_semana', 'horario_inicio'],
                'unique_together': {('dia_semana', 'aula')},
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('RESOLVIDA', 'Resolvida'), ('ARQUIVADA', 'Arquivada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='ocorrencias.aluno', verbose_name='Aluno')),
                ('atualizado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='ocorrencias.horario', verbose_name='Horário')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='ocorrencias.professor', verbose_name='Professor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='ocorrencias.tipoocorrencia', verbose_name='Tipo da Ocorrência')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='AnexoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=ocorrencias.models.caminho_anexo, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Arquivo')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ocorrencias.ocorrencia', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name': 'Anexo da Ocorrência',
                'verbose_name_plural': 'Anexos da Ocorrência',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.CharField(blank=True, max_length=20, verbose_name='SIAPE')),
                ('perfil', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('USUARIO', 'Usuário')], default='USUARIO', max_length=20, verbose_name='Perfil')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='ocorrencias.curso', verbose_name='Área')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_ocorrencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da turma')),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], default='MATUTINO', max_length=20, verbose_name='Turno')),
                ('ano_letivo', models.PositiveIntegerField(verbose_name='Ano letivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='ocorrencias.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-ano_letivo', 'nome'],
                'unique_together': {('nome', 'ano_letivo')},
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='ocorrencias.turma', verbose_name='Turma'),
        ),
    ]
