# Generated by Django 5.1.15 on 2026-07-09 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocorrencias", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinatarioRelatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=150, verbose_name="Nome"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "recebe_segunda",
                    models.BooleanField(default=False, verbose_name="Segunda-feira"),
                ),
                (
                    "recebe_terca",
                    models.BooleanField(default=False, verbose_name="Terça-feira"),
                ),
                (
                    "recebe_quarta",
                    models.BooleanField(default=False, verbose_name="Quarta-feira"),
                ),
                (
                    "recebe_quinta",
                    models.BooleanField(default=False, verbose_name="Quinta-feira"),
                ),
                (
                    "recebe_sexta",
                    models.BooleanField(default=False, verbose_name="Sexta-feira"),
                ),
                (
                    "recebe_sabado",
                    models.BooleanField(default=False, verbose_name="Sábado"),
                ),
                (
                    "recebe_domingo",
                    models.BooleanField(default=False, verbose_name="Domingo"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selecione um usuário já cadastrado, ou deixe em branco e informe nome/e-mail abaixo.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinatarios_relatorio",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário do sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destinatário de Relatório",
                "verbose_name_plural": "Destinatários de Relatório",
                "ordering": ["nome", "email"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("usuario__isnull", False)),
                        fields=("usuario",),
                        name="unico_destinatario_por_usuario",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("usuario__isnull", True)),
                        fields=("email",),
                        name="unico_destinatario_por_email",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("usuario__isnull", False),
                            models.Q(("email", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="destinatario_requer_usuario_ou_email",
                    ),
                ],
            },
        ),
    ]
