# Generated by Django 5.1.15 on 2026-07-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocorrencias", "0002_destinatariorelatorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrencia",
            name="alerta_grave_enviado_em",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Preenchido pelo robô de alerta quando o e-mail de ocorrência grave é enviado.",
                null=True,
                verbose_name="Alerta de gravidade enviado em",
            ),
        ),
    ]
